
modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="cratedelight"
version="1.0.0-1.19.2"
displayName="Crate Delight"
logoFile="logo.png"
authors="Axperty"

description='''An addon for Farmer's Delight that adds more crates to the base game.'''

[[dependencies.cratedelight]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cratedelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cratedelight]]
modId="farmersdelight"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
